---
# Configure Web Server

- name: Install required packages (RedHat)
  when: ansible_os_family == "RedHat"
  yum: name={{ item }} state=installed
  with_items:
    - httpd
- name: Remove packages (RedHat)
  when: ansible_os_family == "RedHat"
  yum: name={{ item }} state=absent
  with_items:
    - nginx
- name:  Start services
  when: ansible_os_family == "RedHat"
  service: name={{ item }} state=started enabled=yes
  with_items:
    - httpd
