---
# Configure Database Server

- name: Install required packages
  yum: name={{ item }} state=installed
  with_items:
    - mysql-server
- name:  Start services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - mysqld
