---
# Main playbook

- hosts: all
  gather_facts: yes
  roles:
    - common

- hosts: webserver
  roles:
    - webserver

- hosts: appserver
  roles:
    - appserver

- hosts: dbserver
  roles:
    - dbserver
