---
- hosts: all
  tasks:
  - name: Install required packages
    yum: name={{ item }} state=installed
    with_items:
      - nginx
  - name:  Start nginx
    service: name=nginx state=started enabled=yes
